- hosts: localhost
  become: true
  tasks:
    - name: Install packages
      apt: name={{item}}
      with_items:
        - htop
        - mc
        - tmux
      get_version:
        major: "9"
        minor: "1"
        build: "14393"
